SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE procedure [dbo].[PR_InsertPRInfo]  
  
@RequestorId     varchar(30),  
@RequestorDept     varchar(50),  
@RequestorPhone varchar(50),  
@GLCode           varchar(15),  
@Priority   varchar(15),  
@CreatedBy   varchar(30),  
@Requesteddate  datetime,  
@Justification     varchar(max),  
@CompanySites     varchar(50),  
@ShipName   varchar(75),  
@ShipCompany   varchar(100),  
@ShipAddrLine1 varchar(100),  
@ShipAddrLine2 varchar(100),  
@ShipCity   varchar(50),  
@ShipState   varchar(50),  
@ShipCountry  varchar(50),  
@ShipZipcode  varchar(20),  
@LastApprovedBy varchar(50),  
@PONumber   varchar(25),  
@Status    varchar(20),  
@PODate   datetime,  
@PaymentTerms varchar(400),  
@FreightTerms varchar(50),  
@Taxable varchar(3),  
@AcctCharged varchar(50),  
@ChangeOrder bit,  
@NewVendor varchar(3),  
@ParentPO varchar(25),  
@Buyer varchar(30),  
@DeptCharged varchar(15),  
@Comments varchar(max),  
@Title varchar(max),  
@ShipElectronic varchar(5),
@Entity  varchar(32) 
  
  
as  
insert into tbl_PurchaseReq (  
    RequestorId     ,  
 RequestorDept     ,  
 RequestorPhone ,  
 GLCode           ,  
 Priority   ,  
 CreatedBy   ,  
 Requesteddate  ,  
 Justification     ,  
 CompanySites,  
 ShipName   ,  
 ShipCompany   ,  
 ShipAddrLine1 ,  
 ShipAddrLine2 ,  
 ShipCity   ,  
 ShipState   ,  
 ShipCountry  ,  
 ShipZipcode  ,  
 LastApprovedBy ,  
 PONumber   ,  
 Status    ,  
 PODate   ,  
 PaymentTerms ,  
 FreightTerms ,  
 Taxable ,  
 AcctCharged ,  
 ChangeOrder,  
 NewVendor,  
 ParentPO,  
 Buyer,  
 DeptCharged,  
 Comments,  
 Title,  
ShipElectronic,  
 CreatedDate,
 Entity  
  
  
)  
values (  
    @RequestorId     ,  
 @RequestorDept     ,  
 @RequestorPhone ,  
 @GLCode           ,  
 @Priority   ,  
 @CreatedBy   ,  
 @Requesteddate  ,  
 @Justification     ,  
 @CompanySites,  
 @ShipName   ,  
 @ShipCompany   ,  
 @ShipAddrLine1 ,  
 @ShipAddrLine2 ,  
 @ShipCity   ,  
 @ShipState   ,  
 @ShipCountry  ,  
 @ShipZipcode  ,  
 @LastApprovedBy ,  
 @PONumber   ,  
 @Status    ,  
 @PODate   ,  
 @PaymentTerms ,  
 @FreightTerms ,  
 @Taxable ,  
 @AcctCharged ,  
@ChangeOrder,  
@NewVendor,   
@ParentPO,   
@Buyer,  
@DeptCharged,  
@Comments,  
@Title,  
@ShipElectronic,  
 getdate(),
 @Entity  
  
  
)  
  
select SCOPE_IDENTITY() as PRId
GO
