IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'ARUBANETWORKS\preddy')
CREATE LOGIN [ARUBANETWORKS\preddy] FROM WINDOWS
GO
CREATE USER [ARUBANETWORKS\preddy] FOR LOGIN [ARUBANETWORKS\preddy]
GO
